# Generated by Django 4.2.9 on 2024-02-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.ImageField(upload_to='imgs/')),
                ('scientific_name', models.CharField(max_length=60)),
                ('isinvasive', models.BooleanField()),
                ('description', models.TextField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
