# Generated by Django 4.2.8 on 2024-01-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kind",
            fields=[
                (
                    "species",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="image/")),
                ("species", models.CharField(blank=True, max_length=50, null=True)),
                ("invasion", models.BooleanField()),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
